import Link from "next/link";
import Image from "next/image";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";
import { pageMetadata } from "../lib/seo";
import styles from "../product-pages.module.css";

export const metadata = pageMetadata("IT M&A Software Platform | MergeVista", "Explore the MergeVista AI-powered platform for connected IT M&A inventories, governance, separation, Day 1 readiness, TSA operations, migration and exit.", "/platform");

const capabilities = [
  { number: "01", label: "Baseline & governance", title: "Establish one governed source of truth", text: "Bring applications, infrastructure, sites, users, contracts and licenses into a deal-specific model—then govern the baseline through accountable review.", points: ["Configurable import, mapping and validation", "Submit, review, approve, freeze and control exceptions"], outcome: "Stop reconciling competing inventories" },
  { number: "02", label: "Dependency intelligence", title: "Make cross-workstream dependencies executable", text: "Connect technology records to the business processes, locations, owners and transition decisions that determine how separation and migration must sequence.", points: ["Cross-domain and cross-site relationship mapping", "Risks, decisions and actions connected to affected inventory"], outcome: "See what must move together" },
  { number: "03", label: "Commercial intelligence", title: "Turn contracts and licenses into execution intelligence", text: "Translate agreements into governed obligations and connect commercial constraints directly to the technology and services they affect.", points: ["AI-assisted extraction with source snippets and human review", "Consents, entitlements, products and coverage relationships"], outcome: "Move commercial and technical readiness together" },
  { number: "04", label: "Program orchestration", title: "Coordinate seller and buyer execution in one workspace", text: "Convert the trusted baseline into workstream, site, milestone and migration plans without losing the ownership and transaction context behind them.", points: ["Role-based access across companies, regions and modules", "Shared RAID, milestones, site plans and execution schedules"], outcome: "Preserve context through every handoff" },
  { number: "05", label: "TSA operations", title: "Operate every TSA service with an exit path", text: "Manage the service as an operational obligation—not simply a line in a tracker—from delivery and consumption through final termination.", points: ["Charges, SLAs, issues, notices and service dependencies", "Exit criteria linked to migration milestones and evidence"], outcome: "Exit sooner without shifting risk" },
  { number: "06", label: "Readiness & control", title: "Prove readiness with evidence—not percentage complete", text: "Give leaders a defensible view of whether the business can operate, responsibilities can transfer and seller dependencies can be removed safely.", points: ["Outcome-based readiness criteria and accountable approvals", "Executive visibility into risk, decisions and missing evidence"], outcome: "Turn status reporting into operational confidence" },
];

export default function PlatformPage(){return <main className={styles.page}>
  <SiteHeader/>
  <header className={styles.hero}><div className={styles.heroInner}>
    <div className={styles.heroCopy}><div className={styles.eyebrow}><span/>The MergeVista platform</div><h1>One operating system for the <em>complete IT M&amp;A journey.</em></h1><p>Connect the inventories, teams, plans, dependencies, decisions and evidence required to move from discovery through separation, Day 1, TSA operations, migration and exit.</p><div className={styles.actions}><Link className={styles.primary} href="/book-a-demo">Book a demo →</Link><Link className={styles.secondary} href="/solutions">Explore solutions</Link></div></div>
    <div className={styles.productFrame} aria-label="MergeVista transition readiness" data-product-reveal><div className={styles.productFrameTop}><span>LIVE PRODUCT VIEW <i>Illustrative sample data</i></span><b>TRANSITION READINESS</b></div><Image src="/product/transition-readiness-enriched.png" alt="MergeVista transition readiness workspace showing evidence-based readiness across inventory workstreams" width={1672} height={941} priority/><div className={`${styles.productCallout} ${styles.calloutReady}`} aria-hidden="true"><b>Evidence-based readiness</b><span>13 of 24 workstreams ready</span></div><div className={`${styles.productCallout} ${styles.calloutAttention}`} aria-hidden="true"><b>Actionable exposure</b><span>11 need attention</span></div></div>
  </div></header>
  <section className={styles.proof}><div><span><b>01</b>Buyer + seller collaboration</span><span><b>02</b>Deal-level access control</span><span><b>03</b>End-to-end traceability</span><span><b>04</b>Human-governed AI</span></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div className={styles.eyebrow}><span/>Core capabilities</div><h2>Control the complete execution system—not another set of trackers.</h2><p>MergeVista connects governed transaction data to the workflows, decisions and evidence required to protect continuity and prove progress across both sides of the deal.</p></div><div className={styles.capabilityGrid}>{capabilities.map((capability)=><article key={capability.number}><div className={styles.capabilityTop}><small>{capability.number}</small><span>{capability.label}</span></div><h3>{capability.title}</h3><p>{capability.text}</p><ul>{capability.points.map((point)=><li key={point}>{point}</li>)}</ul><b>{capability.outcome} →</b></article>)}</div></section>
  <section className={`${styles.section} ${styles.sectionAlt}`}><div className={styles.connected}><div className={styles.sectionHead}><div className={styles.eyebrow}><span/>Connected by design</div><h2>The relationships matter as much as the records.</h2><p>An application is connected to infrastructure, users, data, contracts, licenses, sites and TSA services. MergeVista keeps those dependencies visible as plans and ownership change across the deal.</p></div><div className={styles.productFrame} data-product-reveal><div className={styles.productFrameTop}><span>LIVE PRODUCT VIEW <i>Illustrative sample data</i></span><b>INFRASTRUCTURE INTELLIGENCE</b></div><Image src="/product/server-inventory-enriched.png" alt="MergeVista server inventory showing site, application and TSA disposition relationships" width={1672} height={941}/></div></div></section>
  <section className={styles.aiBand}><div><div className={styles.eyebrow}><span/>MergeVista Intelligence</div><h2>AI grounded in transaction evidence.</h2><p>Accelerate understanding without giving up human control. Recommendations remain connected to source documents, confidence and reviewer approval.</p></div><ul><li>Normalize inventories and identify gaps</li><li>Extract contract, license and TSA obligations</li><li>Surface cross-inventory dependencies and readiness risks</li><li>Generate separation, migration and exit actions for review</li></ul></section>
  <section className={styles.cta}><div><h2>See the complete execution model in action.</h2><p>We will tailor the conversation to your transaction, operating model and priorities.</p></div><Link href="/book-a-demo">Book a demo →</Link></section>
  <SiteFooter/>
</main>}
